### ISSUE TITLE
Error: Apigee Remote Proxy not found at: CONFIGURED

### ISSUE THREAD

**Issue by RainerAtSpirit** [apigee-127/example-project#5]
Running on Windows 8 in MingW32 git bash.
When following the instructions in the readme I'm stuck on step 5 `$ a127 project start`, where I receive the above error message.
I'm new to Apigee so I'm not sure if that's something related to my environment or if I'm just missing something obvious. I've noticed a mismatch of parameters (`secrets.js`) described in step 3, but I'm  neither sure is this is related to the error message nor which values should be filled in.

```javascript.
// create an account at https://enterprise.apigee.com
// deploy the apigee remote proxy to your account
// and fill in the details below
exports.apigee = {
  organization: '',
  uri: '', // remote proxy url ??
  key: '', // remote proxy key ??
  secret: ' ', // remove proxy secret ??
  user: ',
  password: ''
};
```

**Comment by theganyo** [comment]
Hey! Sorry for the trouble. We recently updated the way that you connect to the Apigee service and apparently missed updating this sample. I'll take a look ASAP, but in the meantime, it would probably be better to take a look at this updated example: https://github.com/apigee-127/a127-samples/tree/master/weather-advanced.

**Comment by RainerAtSpirit** [comment]
Thanks for the pointer, I'll give that a try. By glancing through the weather example it seems to be different than this one as only the proxy endpoint can be optionally secured by OAuth.
What I'm looking for is an example where the backend (O365 Active Directory App in my case) is secured by OAuth and the remote proxy uses the app key/id to authenticate against it.

**Comment by theganyo** [comment]
Ok. I've update the README and the swagger.yaml to match our new process. Really, it's just a change in how configuration works: We are now using what we are calling "Services" to represent the configuration of an external service. So instead of automatically creating a proxy for Apigee Accounts, you will just need to create a service called "RemoteProxy" and bind it to your application. The Swagger.yaml change is simply to rename the configuration fields.

**Comment by RainerAtSpirit** [comment]
Thanks. That did it.

**Comment by theganyo** [comment]
Fantastic!
